# Generated by Django 2.0.5 on 2018-05-28 12:38

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180526_1702'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diventiuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='has_agreed_gdpr',
            field=models.NullBooleanField(verbose_name='can we send you confidential emails?'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='language',
            field=models.CharField(blank=True, choices=[('it', 'Italian'), ('en', 'English')], default='en', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
